function [] = ej24()
%EJ24 Summary of this function goes here
%   Detailed explanation goes here
    einstein = imread('einstein.jpg');
    monroe = imread('monroe.jpg');
    highpass = einstein - imgaussfilt(einstein, 10);
    lowpass = imgaussfilt(monroe,6);
    im = lowpass + highpass;
    figure;
    subplot(3,3,1),imshow(monroe),...
    subplot(3,3,2),imshow(einstein),...
    subplot(3,3,3),imshow(im),...
    %We add the black border
    subplot(3,3,4),imshow(padarray(im,[50,50],'post')),...
    subplot(3,3,5),imshow(padarray(im,[100,100],'post')),...
    subplot(3,3,6),imshow(padarray(im,[150,150],'post')),...
    subplot(3,3,7),imshow(padarray(im,[200,200],'post')),...
    subplot(3,3,8),imshow(padarray(im,[250,250],'post')),...
    subplot(3,3,9),imshow(padarray(im,[500,500],'post'));
end
